'use client'

import { useEffect, useMemo, useState } from 'react'
import { blockCatalog, createBlock, type BlockType, type BuilderBlock } from '@/lib/builder'
import { normalizeBlocks, mapTree, removeTree } from '@/lib/builder-tree'

type Props={page:{id:string;title:string;slug:string;content:unknown;status:string}}
type Device='desktop'|'tablet'|'mobile'

export default function VisualBuilder({page}:Props){
 const [blocks,setBlocks]=useState<BuilderBlock[]>(()=>normalizeBlocks(page.content)); const [templates,setTemplates]=useState<any[]>([]); const [selected,setSelected]=useState<string|null>(null)
 const [history,setHistory]=useState<BuilderBlock[][]>([]); const [future,setFuture]=useState<BuilderBlock[][]>([]); const [device,setDevice]=useState<Device>('desktop'); const [saving,setSaving]=useState(''); const [dragged,setDragged]=useState<string|null>(null)
 const selectedBlock=blocks.find(b=>b.id===selected) ?? findSelected(blocks,selected)
 useEffect(()=>{fetch('/api/admin/templates',{cache:'no-store'}).then(r=>r.ok?r.json():{items:[]}).then(x=>setTemplates(x.items||[])).catch(()=>setTemplates([]))},[])
 function commit(next:BuilderBlock[]){setHistory(h=>[...h,structuredClone(blocks)].slice(-50));setFuture([]);setBlocks(next)}
 function add(type:BlockType, parentId?:string, column?:number){const b=createBlock(type); if(parentId){const next=mapTree(blocks,parentId,(parent)=>{if(parent.type!=='columns')return parent;const cols=Array.isArray(parent.props.children)?structuredClone(parent.props.children as unknown[]):[[],[]];const idx=Math.max(0,Math.min(Number(column??0),cols.length-1));if(!Array.isArray(cols[idx]))cols[idx]=[];(cols[idx] as unknown[]).push(b);return {...parent,props:{...parent.props,children:cols}}});commit(next)}else{commit([...blocks,b])}setSelected(b.id)}
 function remove(id:string){commit(removeTree(blocks,id));if(selected===id)setSelected(null)}
 function duplicate(id:string){const original=findSelected(blocks,id);if(!original)return;const copy=cloneWithNewIds(original);const next=insertAfter(blocks,id,copy);commit(next);setSelected(copy.id)}
 function move(id:string,dir:number){const next=reorderSibling(blocks,id,dir);if(next)commit(next)}
 function patch(id:string,key:string,value:unknown){setBlocks(bs=>mapTree(bs,id,b=>({...b,props:{...b.props,[key]:value}})))}
 function patchStyle(id:string,device:Device,key:string,value:string){setBlocks(bs=>mapTree(bs,id,b=>({...b,style:{desktop:{},tablet:{},mobile:{},...(b.style||{}),[device]:{...(b.style?.[device]||{}),[key]:value}}})))}
 function undo(){const h=history.at(-1);if(!h)return;setFuture(f=>[structuredClone(blocks),...f].slice(0,50));setBlocks(h);setHistory(x=>x.slice(0,-1))}
 function redo(){const f=future[0];if(!f)return;setHistory(h=>[...h,structuredClone(blocks)]);setBlocks(f);setFuture(x=>x.slice(1))}
 function dropBlock(type:BlockType,targetId?:string,column?:number){add(type,targetId,column)}
 async function save(status?:string){setSaving('Saving…');try{const csrf=await fetch('/api/admin/csrf',{cache:'no-store'}).then(r=>r.json()).then(x=>x.token);const res=await fetch(`/api/admin/pages/${page.id}`,{method:'PATCH',headers:{'content-type':'application/json','x-csrf-token':csrf},body:JSON.stringify({content:blocks,status:status||page.status})});setSaving(res.ok?(status==='PUBLISHED'?'Published ✓':'Saved ✓'):'Save failed')}catch{setSaving('Save failed')}setTimeout(()=>setSaving(''),2500)}
 const width=device==='desktop'?'min(100%,1200px)':device==='tablet'?'768px':'390px'
 return <div className="builder-shell">
  <header className="builder-top glass"><div><div className="text-xs uppercase tracking-[.18em] text-white/35">Neogenra Visual Studio</div><div className="font-semibold">{page.title} <span className="text-white/30">/{page.slug}</span></div></div><div className="flex flex-wrap items-center gap-2"><button onClick={undo} disabled={!history.length} className="builder-btn">Undo</button><button onClick={redo} disabled={!future.length} className="builder-btn">Redo</button>{(['desktop','tablet','mobile'] as Device[]).map(x=><button key={x} onClick={()=>setDevice(x)} className={device===x?'builder-btn active':'builder-btn'}>{x}</button>)}<button onClick={()=>save()} className="builder-btn">{saving||'Save draft'}</button><button onClick={async()=>{const name=window.prompt('Template name');if(!name)return;const csrf=await fetch('/api/admin/csrf',{cache:'no-store'}).then(r=>r.json()).then(x=>x.token);const res=await fetch('/api/admin/templates',{method:'POST',headers:{'content-type':'application/json','x-csrf-token':csrf},body:JSON.stringify({name,slug:name.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,''),type:'SECTION',content:{blocks}})});if(res.ok){const j=await res.json();setTemplates(t=>[j.item,...t]);setSaving('Template saved ✓');setTimeout(()=>setSaving(''),2000)}}} className="builder-btn">Save template</button><button onClick={()=>save('PUBLISHED')} className="builder-publish">Publish</button></div></header>
  <div className="builder-grid">
   <aside className="builder-panel glass"><h2>Elements</h2><p className="builder-muted">Drag into the canvas. Use columns for nested layouts.</p><div className="builder-template-list"><strong>Reusable templates</strong>{templates.slice(0,8).map(t=><button key={t.id} className="builder-block" onClick={()=>{const incoming=normalizeBlocks(t.content);commit([...blocks,...incoming]);if(incoming[0])setSelected(incoming[0].id)}}><strong>{t.name}</strong><span>{t.type}</span></button>)}</div><div className="builder-palette">{blockCatalog.map(item=><button draggable onDragStart={e=>{e.dataTransfer.setData('block-type',item.type);setDragged(item.type)}} onDragEnd={()=>setDragged(null)} onClick={()=>add(item.type)} key={item.type} className="builder-block"><strong>{item.label}</strong><span>{item.description}</span></button>)}</div></aside>
   <main className="builder-canvas-wrap" onDragOver={e=>e.preventDefault()} onDrop={e=>{const type=e.dataTransfer.getData('block-type') as BlockType;if(type)dropBlock(type)}}><div className="builder-canvas" style={{width}}>{blocks.length===0&&<div className="builder-empty">Drop your first element here</div>}{blocks.map((b,i)=><BuilderNode key={b.id} block={b} selected={selected===b.id} onSelect={setSelected} onMove={move} onDuplicate={duplicate} onDelete={remove} onDrop={dropBlock} onDragStart={setDragged} dragged={dragged} index={i}/>)}</div></main>
   <aside className="builder-panel glass"><h2>Inspector</h2>{selectedBlock?<Inspector block={selectedBlock} device={device} patch={patch} patchStyle={patchStyle}/>:<p className="builder-muted">Select an element to edit content, responsive styling and behavior.</p>}</aside>
  </div>
 </div>
}

function BuilderNode({block,selected,onSelect,onMove,onDuplicate,onDelete,onDrop,onDragStart,dragged,index}:{block:BuilderBlock;selected:boolean;onSelect:(id:string)=>void;onMove:(id:string,dir:number)=>void;onDuplicate:(id:string)=>void;onDelete:(id:string)=>void;onDrop:(type:BlockType,parentId?:string,column?:number)=>void;onDragStart:(id:string)=>void;dragged:string|null;index:number}){
 const p=block.props as Record<string,unknown>
 const columns=block.type==='columns' && Array.isArray(p.children)?p.children as unknown[][]:null
 return <div draggable onDragStart={()=>onDragStart(block.id)} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.stopPropagation();const type=e.dataTransfer.getData('block-type') as BlockType;if(type&&block.type==='columns')onDrop(type,block.id,0)}} onClick={e=>{e.stopPropagation();onSelect(block.id)}} className={selected?'builder-node selected':'builder-node'}>
  <div className="builder-node-tools"><span>{blockCatalog.find(x=>x.type===block.type)?.label||block.type}</span><button onClick={e=>{e.stopPropagation();onMove(block.id,-1)}}>↑</button><button onClick={e=>{e.stopPropagation();onMove(block.id,1)}}>↓</button><button onClick={e=>{e.stopPropagation();onDuplicate(block.id)}}>Duplicate</button><button onClick={e=>{e.stopPropagation();onDelete(block.id)}}>Delete</button></div>
  <BlockPreview block={block}/>
  {columns&&<div className="builder-columns">{columns.map((items,column)=><div key={column} className="builder-column" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.stopPropagation();const type=e.dataTransfer.getData('block-type') as BlockType;if(type)onDrop(type,block.id,column)}}><div className="builder-column-label">Column {column+1} · Drop here</div>{items.map((item:any)=><div key={item.id} className="builder-mini-node" onClick={e=>{e.stopPropagation();onSelect(item.id)}}>{String(item.type)} · {String((item.props||{}).title||'Element')}</div>)}</div>)}</div>}
 </div>
}

function Inspector({block,device,patch,patchStyle}:{block:BuilderBlock;device:Device;patch:(id:string,k:string,v:unknown)=>void;patchStyle:(id:string,d:Device,k:string,v:string)=>void}){
 const entries=useMemo(()=>Object.entries(block.props).filter(([k])=>k!=='children'),[block.props]); const styles=block.style?.[device]||{}
 return <div className="builder-inspector"><div className="builder-inspector-section"><strong>Content</strong>{entries.map(([k,v])=><label key={k}><span>{k}</span>{Array.isArray(v)||typeof v==='object'?<textarea value={JSON.stringify(v,null,2)} onChange={e=>{try{patch(block.id,k,JSON.parse(e.target.value))}catch{}}}/>:<textarea value={String(v??'')} onChange={e=>patch(block.id,k,e.target.value)}/>}</label>)}</div><div className="builder-inspector-section"><strong>Responsive style · {device}</strong>{['maxWidth','width','minHeight','padding','margin','gap','fontSize','lineHeight','letterSpacing','textAlign','background','color','borderRadius','boxShadow','display'].map(key=><label key={key}><span>{key}</span><input value={String((styles as Record<string,unknown>)[key]??'')} onChange={e=>patchStyle(block.id,device,key,e.target.value)} placeholder="inherit"/></label>)}</div></div>
}

function BlockPreview({block}:{block:BuilderBlock}){const p=block.props as any;switch(block.type){case'hero':return <section className="preview-hero"><small>{p.kicker}</small><h1>{p.title}</h1><p>{p.body}</p><span>{p.cta}</span></section>;case'section':case'container':return <section className="preview-card"><small>{p.eyebrow||block.type}</small><h2>{p.title||'Container'}</h2><p>{p.body||'Responsive layout container'}</p></section>;case'columns':return <section className="preview-card"><h2>{p.count||2} columns</h2><p>Nested responsive layout. Drop elements into each column below.</p></section>;case'richText':return <section className="preview-copy">{p.body}</section>;case'image':return <section className="preview-media">{p.src?<img src={p.src} alt={p.alt||''}/>:<div>Image block — choose media</div>}</section>;case'video':return <section className="preview-media">{p.src?<video src={p.src} controls/>:<div>Video block — choose media</div>}</section>;case'stats':return <section className="preview-stats">{(p.items||[]).map((x:any,i:number)=><div key={i}><b>{x.value}</b><small>{x.label}</small></div>)}</section>;case'cta':return <section className="preview-cta"><h2>{p.title}</h2><span>{p.cta}</span></section>;case'spacer':return <div style={{height:Number(p.height)||80}}/>;case'scene3d':return <section className="preview-scene3d"><small>{p.eyebrow||'NEOGENRA / LAB'}</small><h2>{p.title||'A living idea engine'}</h2><div className="preview-3d-object"><i/><i/><i/><i/><i/><i/></div></section>;case'marquee':return <div className="preview-marquee">{Array.isArray(p.items)?p.items.join('  ✦  '):'BRAND  ✦  DIGITAL  ✦  CONTENT'}</div>;default:return <section className="preview-card"><h2>{p.title||block.type}</h2><p>{p.body||'Live dynamic collection'}</p></section>}}

function findSelected(blocks:BuilderBlock[],id:string|null):BuilderBlock|undefined{if(!id)return;for(const b of blocks){if(b.id===id)return b;const f=b.children&&findSelected(b.children,id);if(f)return f;if(b.type==='columns'&&Array.isArray(b.props.children)){for(const col of b.props.children as unknown[][]){const f2=findSelected(col as BuilderBlock[],id);if(f2)return f2}}}}
function cloneWithNewIds(block:BuilderBlock):BuilderBlock{const copy=structuredClone(block);const walk=(b:BuilderBlock)=>{b.id=crypto.randomUUID();b.children?.forEach(walk);if(b.type==='columns'&&Array.isArray(b.props.children))(b.props.children as unknown[][]).forEach(c=>c.forEach((x:any)=>walk(x)))};walk(copy);return copy}
function insertAfter(blocks:BuilderBlock[],id:string,copy:BuilderBlock):BuilderBlock[]{const out:BuilderBlock[]=[];for(const b of blocks){out.push(b);if(b.id===id){out.push(copy);continue}let next=b;if(b.children){const child=insertAfter(b.children,id,copy);if(child.some((x,i)=>x.id===copy.id&&b.children?.[i]?.id!==x.id))next={...next,children:child}}if(b.type==='columns'&&Array.isArray(b.props.children)){const cols=(b.props.children as unknown[][]).map(col=>insertAfter(col as BuilderBlock[],id,copy));next={...next,props:{...next.props,children:cols}}}out[out.length-1]=next}return out}
function reorderSibling(blocks:BuilderBlock[],id:string,dir:number):BuilderBlock[]|null{const idx=blocks.findIndex(b=>b.id===id);if(idx>=0){const j=idx+dir;if(j<0||j>=blocks.length)return null;const next=[...blocks];[next[idx],next[j]]=[next[j],next[idx]];return next}for(const b of blocks){if(b.children){const n=reorderSibling(b.children,id,dir);if(n)return blocks.map(x=>x.id===b.id?{...x,children:n}:x)}if(b.type==='columns'&&Array.isArray(b.props.children)){const cols=b.props.children as unknown[][];for(let i=0;i<cols.length;i++){const n=reorderSibling(cols[i] as BuilderBlock[],id,dir);if(n){const newCols=cols.map((c,k)=>k===i?n:c);return blocks.map(x=>x.id===b.id?{...x,props:{...x.props,children:newCols}}:x)}}}}return null}
