export type SiteDesign = {
  brand: { logoText: string; logoMark: string; tagline: string; footerTagline: string }
  typography: { headingFont: string; bodyFont: string; baseSize: number; displayWeight: number; letterSpacing: string; h1: string; h2: string; h3: string }
  colors: { background: string; surface: string; surfaceAlt: string; text: string; muted: string; primary: string; accent: string; border: string; headerBg: string; footerBg: string }
  layout: { container: string; sectionSpace: string; radius: string; gridGap: string; headerHeight: string }
  header: { style: 'minimal'|'editorial'|'centered'; sticky: boolean; showTopBar: boolean; topBarText: string; ctaLabel: string; ctaHref: string }
  footer: { show: boolean; copyright: string; closingLine: string }
  buttons: { style: 'solid'|'outline'|'text'; radius: string; uppercase: boolean }
  motion: { enabled: boolean; reveal: boolean; hoverLift: boolean; cursor: boolean; transition: string }
  effects: { noise: boolean; grid: boolean; glass: boolean; shadows: boolean }
  seo: { favicon: string; ogImage: string }
}
export const DEFAULT_SITE_DESIGN: SiteDesign = { brand:{logoText:'NEOGENRA®',logoMark:'N',tagline:'Brand × Creative × Digital × Growth × AI.',footerTagline:'A digital creative studio building brands, experiences and growth systems.'},typography:{headingFont:'Inter',bodyFont:'Inter',baseSize:16,displayWeight:700,letterSpacing:'-0.045em',h1:'clamp(3.5rem, 9vw, 8.5rem)',h2:'clamp(2.5rem, 5vw, 5.5rem)',h3:'clamp(1.5rem, 3vw, 2.5rem)'},colors:{background:'#080808',surface:'#111111',surfaceAlt:'#171717',text:'#F5F5F2',muted:'#8C8C87',primary:'#F5F5F2',accent:'#D7FF55',border:'rgba(255,255,255,.14)',headerBg:'rgba(8,8,8,.88)',footerBg:'#050505'},layout:{container:'1280px',sectionSpace:'clamp(5rem, 11vw, 11rem)',radius:'0px',gridGap:'24px',headerHeight:'82px'},header:{style:'minimal',sticky:true,showTopBar:false,topBarText:'',ctaLabel:'Start a project',ctaHref:'/contact'},footer:{show:true,copyright:'© {year} Neogenra. All rights reserved.',closingLine:'Built for what’s next.'},buttons:{style:'outline',radius:'999px',uppercase:false},motion:{enabled:true,reveal:true,hoverLift:true,cursor:false,transition:'420ms cubic-bezier(.2,.8,.2,1)'},effects:{noise:true,grid:false,glass:false,shadows:false},seo:{favicon:'',ogImage:''}}
export function normalizeSiteDesign(value:unknown):SiteDesign{const raw=value&&typeof value==='object'?value as Record<string,unknown>:{};const merge=<T,>(base:T,v:unknown)=>v&&typeof v==='object'&&!Array.isArray(v)?Object.assign({},base,v) as T:base;return {...DEFAULT_SITE_DESIGN,brand:merge(DEFAULT_SITE_DESIGN.brand,raw.brand),typography:merge(DEFAULT_SITE_DESIGN.typography,raw.typography),colors:merge(DEFAULT_SITE_DESIGN.colors,raw.colors),layout:merge(DEFAULT_SITE_DESIGN.layout,raw.layout),header:merge(DEFAULT_SITE_DESIGN.header,raw.header),footer:merge(DEFAULT_SITE_DESIGN.footer,raw.footer),buttons:merge(DEFAULT_SITE_DESIGN.buttons,raw.buttons),motion:merge(DEFAULT_SITE_DESIGN.motion,raw.motion),effects:merge(DEFAULT_SITE_DESIGN.effects,raw.effects),seo:merge(DEFAULT_SITE_DESIGN.seo,raw.seo)}}
