'use client'

import { useEffect, useMemo, useState } from 'react'
import { Check, Eye, LayoutGrid, Palette, Save, Settings2, Type, MousePointer2, PanelTop, PanelBottom, Sparkles, Search } from 'lucide-react'
import { DEFAULT_SITE_DESIGN, type SiteDesign } from '@/lib/site-design'
import styles from './WebsiteDesignStudio.module.css'

type Tab='brand'|'type'|'colors'|'layout'|'header'|'footer'|'buttons'|'motion'|'effects'|'seo'
const tabs:{key:Tab;label:string;icon:typeof Type}[]=[{key:'brand',label:'Brand',icon:Sparkles},{key:'type',label:'Typography',icon:Type},{key:'colors',label:'Colors',icon:Palette},{key:'layout',label:'Layout',icon:LayoutGrid},{key:'header',label:'Header',icon:PanelTop},{key:'footer',label:'Footer',icon:PanelBottom},{key:'buttons',label:'Buttons',icon:MousePointer2},{key:'motion',label:'Motion',icon:Sparkles},{key:'effects',label:'Effects',icon:Settings2},{key:'seo',label:'SEO',icon:Search}]
export default function WebsiteDesignStudio({initial}:{initial:SiteDesign}){
 const [tab,setTab]=useState<Tab>('brand');const [design,setDesign]=useState<SiteDesign>(initial);const [original,setOriginal]=useState(initial);const [csrf,setCsrf]=useState('');const [settingId,setSettingId]=useState('');const [state,setState]=useState('');const [error,setError]=useState('');const dirty=useMemo(()=>JSON.stringify(design)!==JSON.stringify(original),[design,original])
 useEffect(()=>{Promise.all([fetch('/api/admin/content/setting?take=100',{cache:'no-store'}).then(r=>r.json()),fetch('/api/admin/csrf',{cache:'no-store'}).then(r=>r.json())]).then(([settings,token])=>{const item=(settings.items||[]).find((x:any)=>x.key==='design.system');if(item){const v=item.value||{};const merged={...initial,...v,brand:{...initial.brand,...v.brand},typography:{...initial.typography,...v.typography},colors:{...initial.colors,...v.colors},layout:{...initial.layout,...v.layout},header:{...initial.header,...v.header},footer:{...initial.footer,...v.footer},buttons:{...initial.buttons,...v.buttons},motion:{...initial.motion,...v.motion},effects:{...initial.effects,...v.effects},seo:{...initial.seo,...v.seo}} as SiteDesign;setSettingId(item.id);setDesign(merged);setOriginal(merged)}setCsrf(token.token||'')}).catch(()=>setError('Could not load the design system.'))},[initial])
 const set=(group:keyof SiteDesign,key:string,value:any)=>setDesign(d=>({...d,[group]:{...(d[group] as any),[key]:value}}));const reset=()=>setDesign(DEFAULT_SITE_DESIGN)
 async function save(){if(!csrf)return;setState('Saving…');setError('');try{const res=await fetch('/api/admin/content/setting',{method:settingId?'PATCH':'POST',headers:{'Content-Type':'application/json','x-csrf-token':csrf},body:JSON.stringify(settingId?{id:settingId,data:{value:design}}:{key:'design.system',value:design})});const body=await res.json().catch(()=>({}));if(!res.ok)throw new Error(body.error||'Save failed');if(!settingId&&body.item?.id)setSettingId(body.item.id);setOriginal(design);setState('Saved ✓');setTimeout(()=>setState(''),1800)}catch(e){setError((e as Error).message);setState('')}}
 return <div className={styles.studio}><div className={styles.intro}><div><p className={styles.kicker}>DESIGN STUDIO / SITE-WIDE</p><h1>Control the entire experience.</h1><p>Every value below is stored in the CMS and consumed by the public site. No code edit is required for routine visual changes.</p></div><div className={styles.actions}><a href="/" target="_blank" rel="noreferrer" className={styles.preview}><Eye size={15}/> Live site</a><button onClick={reset} className={styles.reset}>Reset defaults</button><button onClick={save} disabled={!dirty||!csrf} className={styles.save}>{state==='Saving…'?'Saving…':state||<><Save size={15}/> Save changes</>}</button></div></div>{error&&<div className={styles.error}>{error}</div>}<div className={styles.workspace}><aside className={styles.tabs}>{tabs.map(t=>{const Icon=t.icon;return <button key={t.key} onClick={()=>setTab(t.key)} className={tab===t.key?styles.active:''}><Icon size={16}/><span>{t.label}</span></button>})}</aside><section className={styles.form}>
 {tab==='brand'&&<><Section title="Brand identity" text="Global identity values used in the header, footer and calls to action."/><Grid><Input label="Logo text" value={design.brand.logoText} onChange={v=>set('brand','logoText',v)}/><Input label="Logo mark" value={design.brand.logoMark} onChange={v=>set('brand','logoMark',v)}/><Input label="Brand tagline" value={design.brand.tagline} onChange={v=>set('brand','tagline',v)}/><Input label="Footer tagline" value={design.brand.footerTagline} onChange={v=>set('brand','footerTagline',v)}/></Grid></>}
 {tab==='type'&&<><Section title="Typography" text="Control the typographic hierarchy across the whole website."/><Grid><Input label="Heading font" value={design.typography.headingFont} onChange={v=>set('typography','headingFont',v)}/><Input label="Body font" value={design.typography.bodyFont} onChange={v=>set('typography','bodyFont',v)}/><NumberField label="Base size" value={design.typography.baseSize} onChange={v=>set('typography','baseSize',v)}/><NumberField label="Display weight" value={design.typography.displayWeight} onChange={v=>set('typography','displayWeight',v)}/><Input label="Display letter spacing" value={design.typography.letterSpacing} onChange={v=>set('typography','letterSpacing',v)}/><Input label="H1 size" value={design.typography.h1} onChange={v=>set('typography','h1',v)}/><Input label="H2 size" value={design.typography.h2} onChange={v=>set('typography','h2',v)}/><Input label="H3 size" value={design.typography.h3} onChange={v=>set('typography','h3',v)}/></Grid></>}
 {tab==='colors'&&<><Section title="Color system" text="One palette controls backgrounds, typography, borders, surfaces, navigation and accents."/><Grid>{Object.entries(design.colors).map(([k,v])=><Color key={k} label={human(k)} value={v} onChange={x=>set('colors',k,x)}/>)}</Grid></>}
 {tab==='layout'&&<><Section title="Global layout" text="Set the site's spatial rhythm and container geometry."/><Grid><Input label="Content max width" value={design.layout.container} onChange={v=>set('layout','container',v)}/><Input label="Section spacing" value={design.layout.sectionSpace} onChange={v=>set('layout','sectionSpace',v)}/><Input label="Corner radius" value={design.layout.radius} onChange={v=>set('layout','radius',v)}/><Input label="Grid gap" value={design.layout.gridGap} onChange={v=>set('layout','gridGap',v)}/><Input label="Header height" value={design.layout.headerHeight} onChange={v=>set('layout','headerHeight',v)}/></Grid></>}
 {tab==='header'&&<><Section title="Header & top bar" text="The header is a CMS-controlled global component."/><Grid><Select label="Header style" value={design.header.style} options={['minimal','editorial','centered']} onChange={v=>set('header','style',v)}/><Toggle label="Sticky header" value={design.header.sticky} onChange={v=>set('header','sticky',v)}/><Toggle label="Show top utility bar" value={design.header.showTopBar} onChange={v=>set('header','showTopBar',v)}/><Input label="Top bar text" value={design.header.topBarText} onChange={v=>set('header','topBarText',v)}/><Input label="Header CTA label" value={design.header.ctaLabel} onChange={v=>set('header','ctaLabel',v)}/><Input label="Header CTA URL" value={design.header.ctaHref} onChange={v=>set('header','ctaHref',v)}/></Grid></>}
 {tab==='footer'&&<><Section title="Footer" text="Control the global closing experience and legal line."/><Grid><Toggle label="Show footer" value={design.footer.show} onChange={v=>set('footer','show',v)}/><Input label="Copyright" value={design.footer.copyright} onChange={v=>set('footer','copyright',v)}/><Input label="Closing line" value={design.footer.closingLine} onChange={v=>set('footer','closingLine',v)}/></Grid></>}
 {tab==='buttons'&&<><Section title="Button system" text="Set the default treatment for calls to action site-wide."/><Grid><Select label="Button style" value={design.buttons.style} options={['solid','outline','text']} onChange={v=>set('buttons','style',v)}/><Input label="Button radius" value={design.buttons.radius} onChange={v=>set('buttons','radius',v)}/><Toggle label="Uppercase labels" value={design.buttons.uppercase} onChange={v=>set('buttons','uppercase',v)}/></Grid></>}
 {tab==='motion'&&<><Section title="Motion & interaction" text="Respect reduced-motion preferences while giving the studio control over interaction intensity."/><Grid><Toggle label="Motion enabled" value={design.motion.enabled} onChange={v=>set('motion','enabled',v)}/><Toggle label="Scroll reveals" value={design.motion.reveal} onChange={v=>set('motion','reveal',v)}/><Toggle label="Hover lift" value={design.motion.hoverLift} onChange={v=>set('motion','hoverLift',v)}/><Toggle label="Custom cursor" value={design.motion.cursor} onChange={v=>set('motion','cursor',v)}/><Input label="Transition" value={design.motion.transition} onChange={v=>set('motion','transition',v)}/></Grid></>}
 {tab==='effects'&&<><Section title="Visual effects" text="Keep the visual language deliberate instead of hard-coding effects into individual components."/><Grid><Toggle label="Texture / noise" value={design.effects.noise} onChange={v=>set('effects','noise',v)}/><Toggle label="Grid overlays" value={design.effects.grid} onChange={v=>set('effects','grid',v)}/><Toggle label="Glass surfaces" value={design.effects.glass} onChange={v=>set('effects','glass',v)}/><Toggle label="Drop shadows" value={design.effects.shadows} onChange={v=>set('effects','shadows',v)}/></Grid></>}
 {tab==='seo'&&<><Section title="Brand SEO assets" text="SEO titles and page metadata live in the dedicated SEO manager; these are the global visual assets."/><Grid><Input label="Favicon URL" value={design.seo.favicon} onChange={v=>set('seo','favicon',v)}/><Input label="Default OG image URL" value={design.seo.ogImage} onChange={v=>set('seo','ogImage',v)}/></Grid></>}
 </section><aside className={styles.previewPane}><div className={styles.previewTop}><span>LIVE STYLE PREVIEW</span><strong>{dirty?'Unsaved changes':'Published configuration'}</strong></div><div className={styles.mock} style={{background:design.colors.background,color:design.colors.text}}><div className={styles.mockHeader} style={{borderColor:design.colors.border}}><b style={{fontFamily:design.typography.headingFont}}>{design.brand.logoText}</b><span>WORK</span><span>SERVICES</span><button style={{background:design.buttons.style==='solid'?design.colors.primary:'transparent',color:design.buttons.style==='solid'?design.colors.background:design.colors.text,borderRadius:design.buttons.radius,border:`1px solid ${design.colors.border}`}}>{design.header.ctaLabel}</button></div><div className={styles.mockBody}><small style={{color:design.colors.accent}}>INDEPENDENT CREATIVE STUDIO</small><h2 style={{fontFamily:design.typography.headingFont,letterSpacing:design.typography.letterSpacing}}>Make the <i>ordinary</i> impossible to ignore.</h2><p style={{color:design.colors.muted}}>A live preview of the global design tokens that every page and component inherits.</p><div className={styles.mockLine} style={{background:design.colors.accent}}/></div></div></aside></div></div>
}
function Section({title,text}:{title:string;text:string}){return <div className={styles.section}><h2>{title}</h2><p>{text}</p></div>}
function Grid({children}:{children:React.ReactNode}){return <div className={styles.grid}>{children}</div>}
function Input({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}){return <label className={styles.field}><span>{label}</span><input value={value} onChange={e=>onChange(e.target.value)}/></label>}
function NumberField({label,value,onChange}:{label:string;value:number;onChange:(v:number)=>void}){return <label className={styles.field}><span>{label}</span><input type="number" value={value} onChange={e=>onChange(globalThis.Number(e.target.value))}/></label>}
function Color({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}){return <label className={styles.field}><span>{label}</span><div className={styles.color}><input type="color" value={value.startsWith('#')?value:'#ffffff'} onChange={e=>onChange(e.target.value)}/><input value={value} onChange={e=>onChange(e.target.value)}/></div></label>}
function Select({label,value,options,onChange}:{label:string;value:string;options:string[];onChange:(v:string)=>void}){return <label className={styles.field}><span>{label}</span><select value={value} onChange={e=>onChange(e.target.value)}>{options.map(x=><option key={x}>{x}</option>)}</select></label>}
function Toggle({label,value,onChange}:{label:string;value:boolean;onChange:(v:boolean)=>void}){return <label className={styles.toggle}><span>{label}</span><button type="button" aria-pressed={value} onClick={()=>onChange(!value)} className={value?styles.toggleOn:''}><i/></button></label>}
function human(s:string){return s.replace(/([A-Z])/g,' $1').replace(/^./,x=>x.toUpperCase())}
