import Link from 'next/link'
import { prisma } from '@/lib/prisma'
import { getSiteDesign } from '@/lib/site-design'
export default async function SiteFooter(){
 const design=await getSiteDesign(); if(!design.footer.show)return null
 let links=[['Work','/work'],['Services','/services'],['About','/about'],['Contact','/contact']]
 try { const nav=await prisma.navigationItem.findMany({where:{enabled:true,parentId:null},orderBy:{sortOrder:'asc'},take:6}); if(nav.length)links=nav.map(x=>[x.label,x.href]) } catch {}
 const year=new Date().getFullYear(); const copyright=design.footer.copyright.replace('{year}',String(year))
 return <footer className="site-footer border-t px-6 py-16" style={{background:design.colors.footerBg,borderColor:design.colors.border,color:design.colors.text}}><div className="mx-auto" style={{maxWidth:design.layout.container}}><div className="grid gap-10 md:grid-cols-3"><div><div className="text-3xl font-black tracking-[-.07em]" style={{fontFamily:design.typography.headingFont}}>{design.brand.logoText}</div><p className="mt-3 max-w-sm" style={{color:design.colors.muted}}>{design.brand.footerTagline}</p></div><div><div className="mb-3 text-xs uppercase tracking-[.2em]" style={{color:design.colors.muted}}>Explore</div>{links.map(([n,h])=><Link className="mr-5 text-sm" style={{color:design.colors.muted}} key={h} href={h}>{n}</Link>)}</div><div><div className="mb-3 text-xs uppercase tracking-[.2em]" style={{color:design.colors.muted}}>Start a project</div><Link href={design.header.ctaHref} className="text-xl underline underline-offset-8" style={{textDecorationColor:design.colors.border}}>{design.header.ctaLabel} →</Link></div></div><div className="mt-16 flex justify-between border-t pt-5 text-xs" style={{borderColor:design.colors.border,color:design.colors.muted}}><span>{copyright}</span><span>{design.footer.closingLine}</span></div></div></footer>}
